name: Onboard students

on:
  workflow_dispatch:

jobs:
  sync-team:
    runs-on: ubuntu-latest
    steps:
      - name: Invite outside collaborator(s) to be a team member
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG: ${{ github.repository_owner }}
          TEAM: ${{ vars.STUDENT_TEAM }}
        run: |
          gh api \
            /orgs/$ORG/outside_collaborators --paginate | \
          jq -r ".[].login" | \
          xargs -I {} \
          gh api \
            --method PUT \
            /orgs/$ORG/teams/$TEAM/memberships/{} \
            -f "role=member"
