name: Onboard students

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0,6,12,16 21-31 1,8 1-5" # Four times per weekday on approximately the start of each semester

jobs:
  sync-team:
    runs-on: ubuntu-latest
    steps:
      - name: Invite outside collaborator(s) to be a team member
        env:
          ORG: ${{ github.repository_owner }}
          TEAM: ${{ vars.STUDENT_TEAM }}
        run: |
          gh api \
            /orgs/$ORG/outside_collaborators --paginate | \
          jq -r ".[].login" | \
            xargs -I {} \
              gh api \
                --method PUT \
                /orgs/$ORG/teams/$TEAM/memberships/{} \
                -f "role=member"
