name: Onboard students

on:
  workflow_dispatch:

jobs:
  sync-team:
    runs-on: ubuntu-latest
    steps:
      - name: Invite students to an organization team
        env:
          GH_TOKEN: ${{ github.token }}
          ORG: ${{ github.repository_owner }}
          STUDENT_TEAM: ${{ vars.STUDENT_TEAM }}
        run: |
          gh api "/orgs/$ORG/outside_collaborators" --paginate \
            | jq -r ".[].login" \
            | xargs -I {} \
                gh api --method PUT "/orgs/$ORG/teams/$STUDENT_TEAM/memberships/{}" -f "role=member"
