name: Sync assignments (sync forks)

on:
  workflow_dispatch:

jobs:
  sync-team:
    runs-on: ubuntu-latest
    steps:
      - name: Sync student forks to assignment source
        env:
          GH_TOKEN: ${{ github.token }}
          ORG: ${{ github.repository_owner }}
          SOURCE: ${{ vars.SOURCE_SLUG }}
        run: |
          gh api orgs/$ORG/repos --paginate \
            | jq ".[].name | select(startswith(\"$SOURCE-\"))" \
            | xargs -I {} sh -c "echo \"Syncing fork {}:\" && gh repo sync \"$ORG/{}\" -s \"$ORG/$SOURCE\""
